stages:
  - build-assets

build:
  image: registry.njuics.cn/nap/dcos-ui-base
  stage: build-assets
  tags:
    - build-in-docker
  script:
    - npm install
    - npm run scaffold
    - npm run build-assets
  artifacts:
    paths:
      - dist
